---
version: '3'
services:
  api:
    build: ./api
    ports:
      - 8080:8080
    networks:
      - front-tier
    depends_on:
      - db
  db:
    image: mysql
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: db
     MYSQL_USER: tony
     MYSQL_PASSWORD: tony
    networks:
      - back-tier

networks:
  front-tier:
  back-tier: